services:

  node:
    environment:
      - NETWORK=${NETWORK:?err}
    healthcheck:
      interval: 10s
      retries: 10
      test: socat -u OPEN:/dev/null UNIX-CONNECT:/ipc/node.socket
      timeout: 5s
    image: inputoutput/cardano-node:1.35.4
    restart: unless-stopped
    volumes:
    - shared:/ipc
    - node-db:/opt/cardano/data

  postgres:
    environment:
    - POSTGRES_LOGGING=true
    - POSTGRES_USER=postgres
    - POSTGRES_PASSWORD=postgres
    - TZ=UTC
    healthcheck:
      interval: 10s
      retries: 5
      test: pg_isready -U postgres
      timeout: 5s
    image: postgres:11.5-alpine
    logging:
      driver: json-file
      options:
        max-file: '10'
        max-size: 200k
    restart: unless-stopped
    volumes:
    - postgres:/var/lib/postgresql/data
    - ./${NETWORK:?err}/init.sql:/docker-entrypoint-initdb.d/init.sql

  chain-indexer:
    environment:
    - NODE_CONFIG=/node/config.json
    - DB_NAME=chain_${NETWORK:?err}
    - DB_USER=postgres
    - DB_PASS=postgres
    - DB_HOST=postgres
    - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
    depends_on:
      node:
        condition: service_healthy
      postgres:
        condition: service_healthy
    image: iohkbuild/marlowe:chain-indexer-20230124
    user: 0:0
    restart: unless-stopped
    volumes:
    - shared:/ipc
    - ./${NETWORK:?err}/node:/node
    - tmp:/tmp

  chainseekd:
    environment:
    - NODE_CONFIG=/node/config.json
    - HOST=0.0.0.0
    - PORT=3715
    - QUERY_PORT=3716
    - JOB_PORT=3720
    - DB_NAME=chain_${NETWORK:?err}
    - DB_USER=postgres
    - DB_PASS=postgres
    - DB_HOST=postgres
    - CARDANO_NODE_SOCKET_PATH=/ipc/node.socket
    depends_on:
      chain-indexer:
        condition: service_started
      postgres:
        condition: service_healthy
    image: iohkbuild/marlowe:chainseekd-20230124
    user: 0:0
    restart: unless-stopped
    volumes:
    - shared:/ipc
    - ./${NETWORK:?err}/node:/node

  discovery:
    environment:
    - HOST=0.0.0.0
    - PORT=3721
    - SYNC_PORT=3722
    - CHAINSEEKD_HOST=chainseekd
    - CHAINSEEKD_PORT=3715
    - CHAINSEEKD_QUERY_PORT=3716
    depends_on:
      - chainseekd
    image: iohkbuild/marlowe:discovery-20230123
    restart: unless-stopped
    ports:
    - 3721
    - 3722

  history:
    environment:
    - HOST=0.0.0.0
    - PORT=3717
    - QUERY_PORT=3718
    - SYNC_PORT=3719
    - CHAINSEEKD_HOST=chainseekd
    - CHAINSEEKD_PORT=3715
    - CHAINSEEKD_QUERY_PORT=3716
    depends_on:
      - chainseekd
    image: iohkbuild/marlowe:history-20230123
    restart: unless-stopped
    ports:
    - 3717
    - 3718
    - 3719

  tx:
    environment:
    - HOST=0.0.0.0
    - PORT=3723
    - CHAINSEEKD_HOST=chainseekd
    - CHAINSEEKD_PORT=3715
    - CHAINSEEKD_QUERY_PORT=3716
    - CHAINSEEKD_COMMAND_PORT=3720
    depends_on:
      - chainseekd
    image: iohkbuild/marlowe:tx-20230123
    restart: unless-stopped
    ports:
    - 3723

volumes:
  node-db: null
  postgres: null
  shared: null
  tmp: null

